In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r"C:\Users\Prabal Kuinkel\Desktop\Data Analyst\100-Days-of-ML\Data-sets\Diet.csv")

In [3]:
df.head()

,Food_items,Breakfast,Lunch,Dinner,VegNovVeg,Junk Food,Calories,Fats,Proteins,Iron,Calcium,Sodium,Potassium,Carbohydrates,Fibre,VitaminD,Sugars
0,Asparagus Cooked,0,1,1,0,0,22,0.2,2.4,0.91,23.0,14.0,224.0,4.1,2.0,0,1.3
1,Avocados,1,0,0,0,0,160,15.0,2.0,0.55,12.0,7.0,485.0,8.5,6.7,0,0.7
2,Bananas,1,0,0,0,0,89,0.3,1.1,0.26,5.0,1.0,358.0,23.0,2.6,0,12.0
3,Bagels made in wheat,0,1,1,0,1,250,1.5,10.0,2.76,20.0,439.0,165.0,49.0,4.1,0,6.1
4,Berries,1,0,0,0,0,349,0.4,14.0,6.80,190.0,298.0,77.0,77.0,13.0,0,46.0

In [4]:
df.sample(20)

,Food_items,Breakfast,Lunch,Dinner,VegNovVeg,Junk Food,Calories,Fats,Proteins,Iron,Calcium,Sodium,Potassium,Carbohydrates,Fibre,VitaminD,Sugars
40,Brownie,1,0,0,0,0,407,6.2,4.4,3.810,17.000,457.0,51.0,84.0,2.9,0,55.00
55,Chia seeds,1,0,0,0,0,486,31.0,17.0,7.720,631.000,16.0,407.0,42.0,34.0,0,0.00
22,Tuna Salad,0,1,1,1,0,187,9.3,16.0,1.000,17.000,402.0,178.0,9.4,0.0,0,0.00
104,Dhido,0,1,1,0,0,100,1.0,50.0,18.000,1000.000,5.0,26.0,1.0,0.0,0,0.00
102,Yomari,0,1,0,0,1,115,1.2,2.2,2.241,1.495,11.7,0.0,22.7,0.0,0,0.00
44,Dal Makhani,0,1,1,0,0,109,8.5,2.1,35.200,8.300,243.0,366.0,6.3,1.5,0,3.29
147,fapher ko roti,0,1,1,0,0,115,7.0,3.0,0.000,80.000,35.0,0.0,10.0,0.0,0,9.00
26,French Fries,0,1,1,0,1,289,14.0,3.5,0.910,17.000,357.0,545.0,37.0,3.9,0,0.30
39,Yogurt,1,1,1,0,0,60,4.0,3.1,0.080,183.000,70.0,234.0,7.0,0.0,1,7.00
11,Dark chocolates,0,0,1,0,1,556,32.0,5.5,2.130,30.000,6.0,502.0,60.0,6.5,0,48.00
64,Strawberries,1,0,0,0,0,32,0.3,0.7,0.410,16.000,1.0,153.0,7.7,2.0,0,4.90
125,aloo paratha,1,1,1,0,0,329,6.2,9.1,3.060,50.000,15.0,982.0,62.3,10.1,0,3.90
92,fried buff momos,0,1,0,1,1,620,22.0,34.0,1.122,0.170,112.0,1021.0,72.0,4.0,0,4.00
13,Milk,1,0,1,0,0,97,6.9,3.8,0.120,169.000,52.0,178.0,5.2,0.0,0,0.00
109,churpii,0,1,1,0,0,20,1.5,2.0,0.000,60.000,82.0,0.0,0.0,0.0,0,0.00
17,Pasta canned with tomato sauce,0,1,1,0,1,71,0.7,2.2,0.910,13.000,381.0,192.0,14.0,0.9,0,4.00
121,khajuri puff,1,0,0,0,1,551,28.0,8.0,0.000,0.000,0.0,0.0,50.0,0.0,0,0.70
29,Chicken Sandwich,0,1,1,1,1,257,12.0,15.0,1.320,92.000,605.0,256.0,23.0,1.2,0,5.00
23,Tuna Fish,0,0,1,1,0,184,6.3,30.0,1.310,10.000,50.0,323.0,0.0,0.0,0,0.00
139,chamsur ko sagg,0,1,1,0,0,90,0.0,3.0,0.720,20.000,690.0,500.0,20.0,3.0,0,4.00

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Food_items     159 non-null    object
 1   Breakfast      159 non-null    int64
 2   Lunch          159 non-null    int64
 3   Dinner         159 non-null    int64
 4   VegNovVeg      159 non-null    int64
 5   Junk Food      159 non-null    int64
 6   Calories       159 non-null    int64
 7   Fats           159 non-null    float64
 8   Proteins       159 non-null    float64
 9   Iron           159 non-null    float64
 10  Calcium        159 non-null    float64
 11  Sodium         159 non-null    float64
 12  Potassium      159 non-null    float64
 13  Carbohydrates  159 non-null    float64
 14  Fibre          159 non-null    float64
 15  VitaminD       159 non-null    int64
 16  Sugars         159 non-null    float64
dtypes: float64(9), int64(7), object(1)
memory usage: 21.2+ KB

In [6]:
df.describe()

,Breakfast,Lunch,Dinner,VegNovVeg,Junk Food,Calories,Fats,Proteins,Iron,Calcium,Sodium,Potassium,Carbohydrates,Fibre,VitaminD,Sugars
count,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000
mean,0.333333,0.679245,0.610063,0.188679,0.270440,218.861635,8.431447,10.208805,2.937956,97.163289,395.671132,183.954717,26.238994,2.474214,6.446541,6.812390
std,0.472894,0.468241,0.489277,0.392490,0.445591,171.892463,10.395356,12.253805,7.120662,220.205893,1595.542612,219.477662,26.132888,4.490922,44.456727,14.374944
min,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,94.000000,0.900000,2.250000,0.095000,2.000000,5.000000,0.300000,6.500000,0.000000,0.000000,0.000000
50%,0.000000,1.000000,1.000000,0.000000,0.000000,172.000000,4.400000,5.200000,0.840000,17.000000,70.000000,123.100000,19.000000,1.000000,0.000000,0.900000
75%,1.000000,1.000000,1.000000,0.000000,1.000000,318.500000,12.000000,13.900000,2.241000,64.000000,370.500000,276.500000,35.500000,2.700000,0.000000,5.700000
max,1.000000,1.000000,1.000000,1.000000,1.000000,812.000000,50.000000,53.900000,57.000000,1250.000000,19506.000000,1129.000000,120.000000,34.000000,435.000000,82.000000

In [7]:
row_count,column_count=df.shape

In [8]:
print('The number of rows',row_count)

The number of rows 159

In [9]:
print('The number of column',column_count)

The number of column 17

In [10]:
breakfast_items = df[df['Breakfast'] == 1][['Food_items', 'VegNovVeg', 'Junk Food', 'Calories', 'Fats', 'Proteins', 'Iron', 'Calcium', 'Sodium', 'Potassium', 'Carbohydrates', 'Fibre', 'VitaminD', 'Sugars']]

In [11]:
breakfast_items.head()

,Food_items,VegNovVeg,Junk Food,Calories,Fats,Proteins,Iron,Calcium,Sodium,Potassium,Carbohydrates,Fibre,VitaminD,Sugars
1,Avocados,0,0,160,15.0,2.0,0.55,12.0,7.0,485.0,8.5,6.7,0,0.7
2,Bananas,0,0,89,0.3,1.1,0.26,5.0,1.0,358.0,23.0,2.6,0,12.0
4,Berries,0,0,349,0.4,14.0,6.80,190.0,298.0,77.0,77.0,13.0,0,46.0
8,American cheese,0,0,331,24.0,20.0,0.84,497.0,966.0,363.0,8.3,0.0,0,0.0
9,Coffee,0,0,2,0.0,0.3,0.02,2.0,1.0,50.0,0.2,0.0,0,0.0

In [13]:
breakfast_items.to_csv('Data-sets/breakfast_items.csv')

In [ ]:
Lunch_items = df[df['Lunch'] == 1][['Food_items', 'VegNovVeg', 'Junk Food', 'Calories', 'Fats', 'Proteins', 'Iron', 'Calcium', 'Sodium', 'Potassium', 'Carbohydrates', 'Fibre', 'VitaminD', 'Sugars']]

In [ ]:
Lunch_items.head()

In [ ]:
Lunch_items.to_csv('/content/drive/MyDrive/KIST_BIT_6_ACADEMIC/ML_Training/Diet_Recommendation_System/lunch_items.csv')

In [ ]:
Dinner_items=df[df['Dinner']==1][['Food_items', 'VegNovVeg', 'Junk Food', 'Calories', 'Fats', 'Proteins', 'Iron', 'Calcium', 'Sodium', 'Potassium', 'Carbohydrates', 'Fibre', 'VitaminD', 'Sugars']]

In [ ]:
Dinner_items.head()

In [ ]:
Dinner_items.to_csv('/content/drive/MyDrive/KIST_BIT_6_ACADEMIC/ML_Training/Diet_Recommendation_System/dinner_items.csv')

In [ ]:
import csv
from sklearn.neighbors import NearestNeighbors
from sklearn.cluster import KMeans
import pandas as pd

class VfcDietRecommendation:
    def __init__(self, age, height, weight, activity_level, body_type):
        self.age = age
        self.height = height
        self.weight = weight
        self.activity_level = activity_level
        self.body_type = body_type
        self.bmr = self.calculate_bmr()

    def calculate_bmr(self):
        if self.body_type == "endomorphic":
            return (10 * self.weight) + (6.25 * self.height) - (5 * self.age) - 161
        elif self.body_type == "ectomorphic":
            return (10 * self.weight) + (6.25 * self.height) - (5 * self.age) + 5
        elif self.body_type == "mesomorphic":
            return (10 * self.weight) + (6.25 * self.height) - (5 * self.age) + 100

    def calculate_calories(self, goal):
        bmr = self.bmr

        if self.activity_level == "sedentary":
            bmr *= 1.2
        elif self.activity_level == "lightly_active":
            bmr *= 1.375
        elif self.activity_level == "moderately_active":
            bmr *= 1.55
        elif self.activity_level == "very_active":
            bmr *= 1.725
        elif self.activity_level == "extra_active":
            bmr *= 1.9

        if goal == "weight_loss":
            return bmr * 0.8
        elif goal == "weight_gain":
            return bmr * 1.2

    def load_food_items(self, csv_file):
        food_items = []
        with open(csv_file, 'r') as file:
            reader = csv.DictReader(file)
            for row in reader:
                food_items.append(row)
        return food_items

    def select_meal(self, food_items, target_calories):
        closest_meal = None
        closest_distance = float('inf')

        for meal in food_items:
            calorie_count = int(meal['Calories'])
            distance = abs(calorie_count - target_calories)

            if distance < closest_distance:
                closest_meal = meal
                closest_distance = distance

        return closest_meal

    def recommend_diet(self, goal, breakfast_csv, lunch_csv, dinner_csv):
        total_calories = self.calculate_calories(goal)

        if goal == "weight_loss":
            breakfast_percentage = 0.3  # 30% of total calories
            lunch_percentage = 0.4  # 40% of total calories
            dinner_percentage = 0.3  # 30% of total calories
        elif goal == "weight_gain":
            breakfast_percentage = 0.25  # 25% of total calories
            lunch_percentage = 0.35  # 35% of total calories
            dinner_percentage = 0.4  # 40% of total calories

        breakfast_calories = total_calories * breakfast_percentage
        lunch_calories = total_calories * lunch_percentage
        dinner_calories = total_calories * dinner_percentage

        breakfast_items = self.load_food_items(breakfast_csv)
        lunch_items = self.load_food_items(lunch_csv)
        dinner_items = self.load_food_items(dinner_csv)

        recommended_diet = {
            "Breakfast": {"Items": [], "Total Calories": 0},
            "Lunch": {"Items": [], "Total Calories": 0},
            "Dinner": {"Items": [], "Total Calories": 0},
        }

        breakfast_meal = self.select_meal(breakfast_items, breakfast_calories)
        lunch_meal = self.select_meal(lunch_items, lunch_calories)
        dinner_meal = self.select_meal(dinner_items, dinner_calories)

        recommended_diet["Breakfast"]["Items"].append(breakfast_meal)
        recommended_diet["Lunch"]["Items"].append(lunch_meal)
        recommended_diet["Dinner"]["Items"].append(dinner_meal)

        if breakfast_meal:
            recommended_diet["Breakfast"]["Total Calories"] += int(breakfast_meal["Calories"])
        if lunch_meal:
            recommended_diet["Lunch"]["Total Calories"] += int(lunch_meal["Calories"])
        if dinner_meal:
            recommended_diet["Dinner"]["Total Calories"] += int(dinner_meal["Calories"])

        return recommended_diet

class DietRecommendationSystem:
    def __init__(self, user):
        self.user = user
        self.breakfast_items = pd.read_csv("/content/drive/MyDrive/KIST_BIT_6_ACADEMIC/ML_Training/Diet_Recommendation_System/breakfast_items.csv")
        self.lunch_items = pd.read_csv("/content/drive/MyDrive/KIST_BIT_6_ACADEMIC/ML_Training/Diet_Recommendation_System/lunch_items.csv")
        self.dinner_items = pd.read_csv("/content/drive/MyDrive/KIST_BIT_6_ACADEMIC/ML_Training/Diet_Recommendation_System/dinner_items.csv")

    def knn_recommendation(self, meal_items, target_calories, k=5):
        X = meal_items[['Calories']].values
        nbrs = NearestNeighbors(n_neighbors=k, algorithm='auto').fit(X)
        distances, indices = nbrs.kneighbors([[target_calories]])
        recommended_items = meal_items.iloc[indices[0]]
        return recommended_items

    def kmeans_recommendation(self, meal_items, target_calories, k=3):
        X = meal_items[['Calories']].values
        kmeans = KMeans(n_clusters=k, random_state=42).fit(X)
        cluster_centers = kmeans.cluster_centers_
        distances = [abs(calories - target_calories) for calories in cluster_centers[:, 0]]
        closest_cluster_index = distances.index(min(distances))
        cluster_items = meal_items[kmeans.labels_ == closest_cluster_index]
        return cluster_items

    def recommend_diet_knn(self, goal):
        total_calories = self.user.calculate_calories(goal)
        breakfast_calories = total_calories * 0.3
        lunch_calories = total_calories * 0.4
        dinner_calories = total_calories * 0.3

        recommended_diet = {
            "Breakfast": self.knn_recommendation(self.breakfast_items, breakfast_calories),
            "Lunch": self.knn_recommendation(self.lunch_items, lunch_calories),
            "Dinner": self.knn_recommendation(self.dinner_items, dinner_calories)
        }

        return recommended_diet

    def recommend_diet_kmeans(self, goal):
        total_calories = self.user.calculate_calories(goal)
        breakfast_calories = total_calories * 0.3
        lunch_calories = total_calories * 0.4
        dinner_calories = total_calories * 0.3

        recommended_diet = {
            "Breakfast": self.kmeans_recommendation(self.breakfast_items, breakfast_calories),
            "Lunch": self.kmeans_recommendation(self.lunch_items, lunch_calories),
            "Dinner": self.kmeans_recommendation(self.dinner_items, dinner_calories)
        }

        return recommended_diet

# Define the variables
age = 20
height = 167.64
weight = 54
activity_level = "moderately_active"
body_type = "ectomorphic"

# Usage
user = VfcDietRecommendation(age, height, weight, activity_level, body_type)
diet_system = DietRecommendationSystem(user)

# K-NN recommendation
recommended_diet_knn = diet_system.recommend_diet_knn("weight_gain")
print("\nRecommended Diet for Weight Gain (K-NN):")
print("Breakfast:\n", recommended_diet_knn["Breakfast"])
print("Lunch:\n", recommended_diet_knn["Lunch"])
print("Dinner:\n", recommended_diet_knn["Dinner"])

# K-Means recommendation
recommended_diet_kmeans = diet_system.recommend_diet_kmeans("weight_gain")
print("\nRecommended Diet for Weight Gain (K-Means):")
print("Breakfast:\n", recommended_diet_kmeans["Breakfast"])
print("Lunch:\n", recommended_diet_kmeans["Lunch"])
print("Dinner:\n", recommended_diet_kmeans["Dinner"])